name: CI
on: [push, pull_request]
jobs:
  build:
    name: Build & test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - node-version: 20.x
          - node-version: 22.x
          - node-version: 'v22.20.0'
            deploys-docs: true
          - node-version: 24.x
          - node-version: '*'

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          check-latest: true
          cache: 'npm'
          cache-dependency-path: 'package.json'

      - run: npm install
      - run: npm run build
      - run: npm test

      - name: Upload docs artifact
        uses: actions/upload-artifact@v6
        if: matrix.deploys-docs == true
        with:
          name: typedoc
          path: typedoc
          retention-days: 1

  deploy-docs:
    name: Deploy docs
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
      - uses: actions/download-artifact@v7
        with:
          name: typedoc
          path: typedoc
      - name: Check for generated docs
        run: |
          # Fails if directory doesn't exist or is empty
          if [ ! -d "typedoc" ] || [ -z "$(ls -A typedoc)" ]; then
            echo "Error: 'typedoc' directory is missing or empty."
            exit 1
          fi
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          single-commit: true
          branch: gh-pages
          folder: typedoc
